[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.10
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
    jgromes/RadioLib@^6.5.0

build_flags =
    -D LORA_FREQ=868.0
    -D TFT_RGB_ORDER=TFT_RGB
    -D ST7789_DRIVER
